### ISSUE TITLE
Exit analysis early if no ID manager is available

### ISSUE THREAD

**Issue by wolfgangmauerer** [siemens/codeface#49]
When the ID manager is not available (most likely because the user forgot to start the
service), Codeface first finished VCS analysis part 1 and then throws a no completly
helpful error message:

```
2016-05-09 18:56:07 [codeface.util] MainProcess CRITICAL: Uncaught exception in worker thread:
Traceback (most recent call last):                                                       | ETA:  --:--:--
  File "/usr/local/bin/codeface", line 9, in <module>
    load_entry_point('codeface', 'console_scripts', 'codeface')()
(...)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
```

The front-end should check the availability of the ID manager at startup (of course only for the passes that require ID services), and exit early with a proper error message if the service is not available.

**Comment by wolfgangmauerer** [comment]
For vagrant based deployments, Codeface should automatically start the ID manager because
paths to configuration files are clear in this case.
